### ISSUE TITLE
System would shutdown unexpectedly

### ISSUE THREAD

**Issue by Suxto** [CoolestEnoch/surface-go3-opencore#1]
It would power off unexpectedly while meeting a high stress. But it doesn't feel hot for me, the temperature could be much higher under Windows 11 xd. I have tried to use votageshift to lower the power, but it doesn't work.

**Comment by CoolestEnoch** [comment]
Sorry for my email application error that I can't receive these messages XD.

I found the same issue with you when I was using the touchscreen version `config.plist` of Ventura, especially when I plug-in & out my Surface Keyboard, it would shutdown unexpectedly. However I didn't found this issue on keyboard version and the version that supports Sonoma.
